# Используем базовый образ Python
FROM python:3.9-slim

# Устанавливаем зависимости
RUN pip install --no-cache-dir scrapy

# Создаем директории
WORKDIR /app

# Копируем файлы проекта
COPY . /app

# Указываем путь к Volume
VOLUME ["/data"]

# Запускаем паука
CMD ["scrapy", "crawl", "sprint"]
