# Базовый образ с Python и Scrapy
FROM python:3.11-slim

# Устанавливаем зависимости
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код паука
COPY . /app

# Создаем папку для данных (если Volume не примонтирован)
RUN mkdir -p /data

# Запуск Scrapy паука
CMD ["scrapy", "crawl", "extractor"]
